name: Build

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'images/**'
      - 'sounds/**'
      - 'src/**'
      - 'build-*.sh'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'images/**'
      - 'sounds/**'
      - 'src/**'
      - 'build-*.sh'

jobs:
  build-mingw:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - { sys: mingw32, env: i686, arch: x86, libwebp: 1.5.0, sdl: 2.32.8, sdl_mixer: 2.8.1 }

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.sys }}
          install: mingw-w64-${{ matrix.env }}-gcc unzip zip

      - name: Setup dependencies
        shell: msys2 {0}
        run: |
          mkdir -p deps
          wget -qO- https://github.com/webmproject/libwebp/archive/refs/tags/v${{ matrix.libwebp }}.tar.gz | tar zxvf - -C deps
          mv deps/libwebp-${{ matrix.libwebp }} deps/libwebp

          wget -qO- https://github.com/libsdl-org/SDL/releases/download/release-${{ matrix.sdl }}/SDL2-devel-${{ matrix.sdl }}-mingw.tar.gz | tar zxvf - -C deps
          mv deps/SDL2-${{ matrix.sdl }} deps/SDL2
          wget -qP deps https://github.com/libsdl-org/SDL/releases/download/release-${{ matrix.sdl }}/SDL2-${{ matrix.sdl }}-win32-${{ matrix.arch }}.zip
          unzip -od deps/SDL2 deps/SDL2-${{ matrix.sdl }}-win32-${{ matrix.arch }}.zip

          wget -qO- https://github.com/libsdl-org/SDL_mixer/releases/download/release-${{ matrix.sdl_mixer }}/SDL2_mixer-devel-${{ matrix.sdl_mixer }}-mingw.tar.gz | tar zxvf - -C deps
          mv deps/SDL2_mixer-${{ matrix.sdl_mixer }} deps/SDL2_mixer
          wget -qP deps https://github.com/libsdl-org/SDL_mixer/releases/download/release-${{ matrix.sdl_mixer }}/SDL2_mixer-${{ matrix.sdl_mixer }}-win32-${{ matrix.arch }}.zip
          unzip -od deps/SDL2_mixer deps/SDL2_mixer-${{ matrix.sdl_mixer }}-win32-${{ matrix.arch }}.zip

          cp deps/SDL2/SDL2.dll .
          cp deps/SDL2_mixer/SDL2_mixer.dll .
          cp deps/SDL2_mixer/optional/libogg-0.dll .

      - name: Build MinGW
        shell: msys2 {0}
        run: |
          ./build-${{ matrix.sys }}.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: game-win32-${{ matrix.env }}
          path: |
            *.exe
            *.dll
            images/*
            sounds/*
